=== AbandonedScope/xmltask/src/main/resources/schema/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/gems"
        xmlns:tns="http://www.example.org/gems"
        elementFormDefault="qualified">
    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <simpleType name="gemID">
        <restriction base="ID">
            <pattern value="\w{8,20}"/>
        </restriction>
    </simpleType>
    <complexType name="gem">
        <sequence>
            <element name="name" type="string"/>
            <element name="visual-parameters" type="tns:visual-parameters"/>
        </sequence>
        <attribute name="id" type="tns:gemID" use="required"/>
        <attribute name="production-date" type="gYearMonth" use="optional"/>
    </complexType>

    <complexType name="preciousStone">
        <complexContent>
            <extension base="tns:gem">
                <sequence>
                    <element name="origin" type="tns:origin"/>
                    <element name="preciousness" type="tns:preciousness"/>
                </sequence>
                <attribute name="faces" type="tns:faces" use="optional"/>
                <attribute name="value" type="tns:carat" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="carat">
        <restriction base="unsignedInt">
            <minExclusive value="0"/>
        </restriction>
    </simpleType>

    <complexType name="jewelryOrnamentalStone">
        <complexContent>
            <extension base="tns:gem">
                <sequence>
                    <element name="animal-producer" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="preciousness">
        <restriction base="string">
            <enumeration value="Precious"/>
            <enumeration value="Semi-precious"/>
            <enumeration value="Non"/>
        </restriction>
    </simpleType>
    <complexType name="origin">
        <sequence>
            <element name="country" type="string"/>
            <element name="mine-name" type="string"/>
        </sequence>
    </complexType>
    <complexType name="visual-parameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="transparency" type="tns:transparency"/>
        </sequence>
    </complexType>
    <simpleType name="transparency">
        <restriction base="unsignedInt">
            <minInclusive value="0"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>
    <simpleType name="faces">
        <restriction base="unsignedInt">
            <minInclusive value="4"/>
            <maxInclusive value="15"/>
        </restriction>
    </simpleType>

    <element name="gem" type="tns:gem" abstract="true"/>
    <element name="precious-stone" type="tns:preciousStone" substitutionGroup="tns:gem"/>
    <element name="jewelry-ornamental-stone" type="tns:jewelryOrnamentalStone" substitutionGroup="tns:gem"/>
</schema>

=== AbandonedScope/xmltask/src/test/resources/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns="http://www.example.org/gems"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.example.org/gems schema/schema.xsd">
    <precious-stone id="fb8cvb13r" production-date="2020-07" value="5">
        <name>Opal</name>
        <visual-parameters>
            <color>Blue</color>
            <transparency>0</transparency>
        </visual-parameters>
        <origin>
            <country>Australia</country>
            <mine-name>Coober Pedy</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <precious-stone id="cv58vb13d" value="7" faces="15">
        <name>Diamond</name>
        <visual-parameters>
            <color>Colorless</color>
            <transparency>100</transparency>
        </visual-parameters>
        <origin>
            <country>Republic of South Africa</country>
            <mine-name>Kimberley</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <jewelry-ornamental-stone id="v7891vxf2">
        <name>Pearl</name>
        <visual-parameters>
            <color>Mother of Pearl</color>
            <transparency>0</transparency>
        </visual-parameters>
        <animal-producer>Pinctada margaritifera</animal-producer>
    </jewelry-ornamental-stone>
    <precious-stone value="12" id="fsgdf43r" >
        <name>Malachite</name>
        <visual-parameters>
            <color>Green</color>
            <transparency>0</transparency>
        </visual-parameters>
        <origin>
            <country>United States</country>
            <mine-name>Arizona</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <precious-stone id="cvx21egvf" faces="12" value="3">
        <name>Elbaite</name>
        <visual-parameters>
            <color>Green</color>
            <transparency>30</transparency>
        </visual-parameters>
        <origin>
            <country>Brazil</country>
            <mine-name>Cruziero pegmatite</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <jewelry-ornamental-stone production-date="1970-05" id="urigkf5551" >
        <name>Amber</name>
        <visual-parameters>
            <color>Yellow</color>
            <transparency>20</transparency>
        </visual-parameters>
        <animal-producer>Sequoia sempervirens</animal-producer>
    </jewelry-ornamental-stone>
    <jewelry-ornamental-stone id="fdxfc21ms" production-date="1890-03">
        <name>Bone</name>
        <visual-parameters>
            <color>White</color>
            <transparency>0</transparency>
        </visual-parameters>
        <animal-producer>Elephant</animal-producer>
    </jewelry-ornamental-stone>
    <precious-stone production-date="1993-07" id="rty54vkh56" value="6">
        <name>Quartz</name>
        <visual-parameters>
            <color>Rose</color>
            <transparency>70</transparency>
        </visual-parameters>
        <origin>
            <country>Spain</country>
            <mine-name>Caldoveiro Peak</mine-name>
        </origin>
        <preciousness>Semi-precious</preciousness>
    </precious-stone>
    <precious-stone id="jjfv25xbsd" value="13">
        <name>Quartz</name>
        <visual-parameters>
            <color>Brown-grey</color>
            <transparency>50</transparency>
        </visual-parameters>
        <origin>
            <country>Scotland</country>
            <mine-name>Cairngorm Mountains</mine-name>
        </origin>
        <preciousness>Semi-precious</preciousness>
    </precious-stone>
    <jewelry-ornamental-stone production-date="2003-06" id="sdgf231dfg">
        <name>Pearl</name>
        <visual-parameters>
            <color>Mother of Pearl</color>
            <transparency>0</transparency>
        </visual-parameters>
        <animal-producer>Indian volute</animal-producer>
    </jewelry-ornamental-stone>
    <precious-stone id="tsdfjb544d" value="5">
        <name>Ruby</name>
        <visual-parameters>
            <color>Purplish red</color>
            <transparency>40</transparency>
        </visual-parameters>
        <origin>
            <country>Shan State</country>
            <mine-name>Mogok Valley</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <precious-stone id="vbvNgf65NKL" value="8">
        <name>Pyrite</name>
        <visual-parameters>
            <color>Pale brass-yellow reflective</color>
            <transparency>0</transparency>
        </visual-parameters>
        <origin>
            <country>India</country>
            <mine-name>Jharkhand</mine-name>
        </origin>
        <preciousness>Semi-precious</preciousness>
    </precious-stone>
    <precious-stone id="hgDmFRkBgv65" value="12" production-date="2006-05">
        <name>Aquamarine</name>
        <visual-parameters>
            <color>Pale-blue</color>
            <transparency>10</transparency>
        </visual-parameters>
        <origin>
            <country>Brazil</country>
            <mine-name>Bahia</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <precious-stone id="nbG15nFk" production-date="2000-07" value="5">
        <name>Opal</name>
        <visual-parameters>
            <color>Green</color>
            <transparency>0</transparency>
        </visual-parameters>
        <origin>
            <country>Australia</country>
            <mine-name>Coober Pedy</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
    <precious-stone id="bDjgC415V" value="12">
        <name>Quartz</name>
        <visual-parameters>
            <color>Yellow</color>
            <transparency>70</transparency>
        </visual-parameters>
        <origin>
            <country>Scotland</country>
            <mine-name>Cairngorm Mountains</mine-name>
        </origin>
        <preciousness>Semi-precious</preciousness>
    </precious-stone>
    <precious-stone id="ZXjhf458dvj" value="10" production-date="2008-02">
        <name>Adamite</name>
        <visual-parameters>
            <color>Honey-yellow</color>
            <transparency>10</transparency>
        </visual-parameters>
        <origin>
            <country>United States</country>
            <mine-name>Sierra Nevada</mine-name>
        </origin>
        <preciousness>Precious</preciousness>
    </precious-stone>
</gems>
